CREATE TABLE IF NOT EXISTS race_state_driver_lap_fact (
    race_state_driver_lap_id VARCHAR PRIMARY KEY,
    session_id VARCHAR,
    meeting_id VARCHAR,
    season_id VARCHAR,
    driver_id VARCHAR,
    constructor_id VARCHAR,
    lap_number INT,
    race_lap_pct DOUBLE,
    laps_remaining INT,
    current_position INT,
    starting_position INT,
    positions_gained_lost INT,
    gap_to_leader_seconds DOUBLE,
    interval_ahead_seconds DOUBLE,
    interval_behind_seconds DOUBLE,
    driver_ahead_id VARCHAR,
    driver_behind_id VARCHAR,
    current_compound_id VARCHAR,
    current_compound_label VARCHAR,
    stint_number INT,
    stint_age_laps INT,
    total_pit_stops INT,
    last_pit_lap INT,
    lap_time_ms DOUBLE,
    rolling_3_lap_avg_ms DOUBLE,
    rolling_5_lap_avg_ms DOUBLE,
    pace_delta_to_field_ms DOUBLE,
    track_status_normalized VARCHAR,
    safety_car_active_flag BOOLEAN,
    virtual_safety_car_active_flag BOOLEAN,
    red_flag_active_flag BOOLEAN,
    rainfall_flag BOOLEAN,
    air_temperature DOUBLE,
    track_temperature DOUBLE,
    pit_window_open_flag BOOLEAN,
    undercut_threat_flag BOOLEAN,
    overcut_opportunity_flag BOOLEAN,
    source_coverage_quality VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS race_state_field_lap (
    race_state_field_lap_id VARCHAR PRIMARY KEY,
    session_id VARCHAR,
    lap_number INT,
    leader_driver_id VARCHAR,
    total_running_drivers INT,
    total_retired_drivers INT,
    safety_car_active_flag BOOLEAN,
    virtual_safety_car_active_flag BOOLEAN,
    red_flag_active_flag BOOLEAN,
    rainfall_flag BOOLEAN,
    average_lap_time_ms DOUBLE,
    median_lap_time_ms DOUBLE,
    fastest_lap_time_ms DOUBLE,
    number_on_soft INT,
    number_on_medium INT,
    number_on_hard INT,
    number_on_intermediate INT,
    number_on_wet INT,
    field_spread_seconds DOUBLE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS race_state_decision_point (
    decision_point_id VARCHAR PRIMARY KEY,
    session_id VARCHAR,
    driver_id VARCHAR,
    lap_number INT,
    decision_type VARCHAR,
    scenario_title VARCHAR,
    scenario_description VARCHAR,
    available_actions_json VARCHAR,
    actual_decision VARCHAR,
    actual_outcome_summary VARCHAR,
    explanation_short VARCHAR,
    explanation_long VARCHAR,
    current_position INT,
    gap_ahead_seconds DOUBLE,
    gap_behind_seconds DOUBLE,
    compound VARCHAR,
    stint_age_laps INT,
    laps_remaining INT,
    track_temperature_c DOUBLE,
    air_temperature_c DOUBLE,
    rainfall BOOLEAN,
    track_status VARCHAR,
    safety_car_active BOOLEAN,
    virtual_safety_car_active BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
